### ISSUE TITLE
Search bar

### ISSUE THREAD

**Issue by wittibs** [mdoleh/WatchYourBAC#1]
As a beer drinker, I would like to search for beers in a search bar and have my search results listed below in order to add beers to the BAC calculation.

Given I enter "Great Lakes" into the search bar,
When I submit the search query
Then I expect a list of Great Lakes fine brews to display below.

Given I have a current selection of beers displayed,
When I clear the search results
Then I expect the search bar to clear as well as the list of beers.

**Comment by mdoleh** [comment]
Perhaps it shouldn't be bound to keyUp since this is intended for use on devices, it's possible they will have a slow connection making typing painfully slow.

Edit: Would also cause problems if you type really fast. The results would not show up correctly. I would suggest a Search button to trigger the calls that gets disabled until the call returns to prevent spamming the button.

**Comment by wittibs** [comment]
@mdoleh I added search button and clear buttons. let me know what you think

**Comment by mdoleh** [comment]
@RyanWittibschlager looks good! Closing this issue.
